// DOM Elements
const startScreen = document.getElementById("start-screen");
const quizScreen = document.getElementById("quiz-screen");
const endScreen = document.getElementById("end-screen");
const questionElement = document.getElementById("question");
const optionsElement = document.getElementById("options");
const feedbackElement = document.getElementById("feedback");
const nextButton = document.getElementById("next-btn");
const progressBar = document.getElementById("progress-bar");
const backgroundMusic = document.getElementById("background-music");
const muteButton = document.getElementById("mute-btn");
const unmuteButton = document.getElementById("unmute-btn");
const startButton = document.getElementById("start-btn");
const usernameInput = document.getElementById("username");
const playAgainButton = document.getElementById("play-again-btn");
const finalScoreElement = document.getElementById("final-score");
const endMessageElement = document.getElementById("end-message");

// Quiz Data
const questions = [
    {
        question: "What is the main greenhouse gas responsible for global warming?",
        options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
        answer: "Carbon Dioxide",
        explanation: "Carbon Dioxide (CO2) is the primary greenhouse gas emitted by human activities."
    },
    {
        question: "Which of the following is a renewable energy source?",
        options: ["Coal", "Natural Gas", "Wind", "Oil"],
        answer: "Wind",
        explanation: "Wind energy is renewable as it is generated by natural processes that are continuously replenished."
    },
    {
        question: "What is the effect of deforestation on climate change?",
        options: ["Increases CO2", "Reduces CO2", "No impact", "Lowers temperatures"],
        answer: "Increases CO2",
        explanation: "Deforestation increases CO2 levels because trees absorb carbon dioxide during photosynthesis."
    },
    {
        question: "What percentage of the Earth's water is freshwater?",
        options: ["3%", "50%", "20%", "75%"],
        answer: "3%",
        explanation: "Only 3% of Earth's water is freshwater, and much of it is frozen in glaciers and ice caps."
    },
    {
        question: "Which gas is mainly responsible for the depletion of the ozone layer?",
        options: ["Carbon Dioxide", "Chlorofluorocarbons (CFCs)", "Methane", "Nitrogen"],
        answer: "Chlorofluorocarbons (CFCs)",
        explanation: "CFCs are responsible for depleting the ozone layer, leading to increased UV radiation reaching the Earth's surface."
    },
    {
        question: "Which energy source is non-renewable?",
        options: ["Solar", "Wind", "Coal", "Hydroelectric"],
        answer: "Coal",
        explanation: "Coal is a non-renewable energy source because it takes millions of years to form."
    },
    {
        question: "What is the primary cause of sea level rise?",
        options: ["Melting glaciers", "Volcanic eruptions", "Earthquakes", "Solar flares"],
        answer: "Melting glaciers",
        explanation: "Melting glaciers and polar ice caps due to global warming contribute to rising sea levels."
    },
    {
        question: "What is the term for the warming of Earth due to trapped heat from the atmosphere?",
        options: ["Greenhouse effect", "El Niño", "Acid rain", "Ozone depletion"],
        answer: "Greenhouse effect",
        explanation: "The greenhouse effect occurs when gases like CO2 trap heat in Earth's atmosphere, warming the planet."
    },
    {
        question: "Which of the following is a major contributor to deforestation?",
        options: ["Urbanization", "Farming", "Mining", "All of the above"],
        answer: "All of the above",
        explanation: "Urbanization, farming, and mining all contribute to deforestation by clearing forests for land use."
    },
    {
        question: "Which type of farming reduces biodiversity?",
        options: ["Monoculture farming", "Crop rotation", "Permaculture", "Agroforestry"],
        answer: "Monoculture farming",
        explanation: "Monoculture farming reduces biodiversity by growing the same crop repeatedly, depleting soil nutrients."
    }
];

const hardQuestions = [
    {
        question: "Which country emits the most carbon dioxide annually?",
        options: ["United States", "China", "India", "Russia"],
        answer: "China",
        explanation: "China emits the most CO2 due to its large population and heavy reliance on coal for energy."
    },
    {
        question: "What is the primary source of methane emissions?",
        options: ["Landfills", "Coal mining", "Agriculture", "Oil extraction"],
        answer: "Agriculture",
        explanation: "Agriculture, especially livestock farming, is the largest source of methane emissions."
    },
    {
        question: "What is the average global temperature rise target set by the Paris Agreement?",
        options: ["1°C", "2°C", "3°C", "4°C"],
        answer: "2°C",
        explanation: "The Paris Agreement aims to limit global temperature rise to well below 2°C above pre-industrial levels."
    },
    {
        question: "What percentage of the world’s electricity is produced by renewable sources?",
        options: ["10%", "25%", "35%", "50%"],
        answer: "25%",
        explanation: "As of recent reports, about 25% of global electricity is generated from renewable sources like wind, solar, and hydroelectric power."
    },
    {
        question: "Which region of the world is experiencing the fastest temperature increase?",
        options: ["Antarctica", "Africa", "The Arctic", "South America"],
        answer: "The Arctic",
        explanation: "The Arctic is warming twice as fast as the global average due to climate change."
    }
];

let currentQuestionIndex = 0;
let score = 0;
let username = "";

// Start Game
startButton.addEventListener("click", () => {
    username = usernameInput.value.trim();
    if (!username) {
        alert("Please enter your name to start the quiz!");
        return;
    }
    startScreen.style.display = "none";
    quizScreen.style.display = "block";
    backgroundMusic.play();
    loadQuestion();
});

// Load Question
function loadQuestion() {
    const questionData = questions[currentQuestionIndex];
    questionElement.textContent = questionData.question;
    optionsElement.innerHTML = ""; // Clear options
    questionData.options.forEach(option => {
        const button = document.createElement("button");
        button.textContent = option;
        button.addEventListener("click", () => handleAnswer(option, questionData.answer, questionData.explanation));
        optionsElement.appendChild(button);
    });
    feedbackElement.innerHTML = "";
    nextButton.style.display = "none";
    updateProgressBar();
}

// Handle Answer
function handleAnswer(selectedOption, correctAnswer, explanation) {
    if (selectedOption === correctAnswer) {
        score++;
        feedbackElement.innerHTML = `<span style="color: green;">Correct!</span> ${explanation}`;
    } else {
        feedbackElement.innerHTML = `<span style="color: red;">Wrong!</span> ${explanation}`;
    }
    nextButton.style.display = "inline-block";
}

// Next Question
nextButton.addEventListener("click", () => {
    currentQuestionIndex++;
    if (currentQuestionIndex < questions.length) {
        loadQuestion();
    } else {
        showFinalScreen();
    }
});

// Show Final Screen
function showFinalScreen() {
    quizScreen.style.display = "none";
    endScreen.style.display = "block";
    finalScoreElement.textContent = `Your final score: ${score}/${questions.length}`;
    endMessageElement.textContent = `Well done, ${username}!`;
}

// Play Again
playAgainButton.addEventListener("click", () => {
    score = 0;
    currentQuestionIndex = 0;
    endScreen.style.display = "none";
    startScreen.style.display = "block";
    usernameInput.value = "";
});

// Update Progress Bar
function updateProgressBar() {
    const progress = ((currentQuestionIndex + 1) / questions.length) * 100;
    progressBar.style.width = `${progress}%`;
}

// Mute/Unmute Music
muteButton.addEventListener("click", () => {
    backgroundMusic.pause();
    muteButton.style.display = "none";
    unmuteButton.style.display = "inline-block";
});

unmuteButton.addEventListener("click", () => {
    backgroundMusic.play();
    unmuteButton.style.display = "none";
    muteButton.style.display = "inline-block";
});
